#### Enivronment Setting for notebook

In [171]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

# Practice

### DataFrame

In [172]:
import numpy as np
import pandas as pd
import time

In [173]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001, 2002, 2003],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

frame = pd.DataFrame(data)
# frame

frame.head()

frame.tail()

frame[::-1]

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

    state  year  pop
5  Nevada  2003  3.2
4  Nevada  2002  2.9
3  Nevada  2001  2.4
2    Ohio  2002  3.6
1    Ohio  2001  1.7
0    Ohio  2000  1.5

In [174]:
frame
frame.shape

pd.DataFrame(data, columns=['year', 'state', 'pop']) # re-arange columns

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

(6, 3)

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [175]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt']) # a column that isn’t contained in the dictionary, it will appear with missing values
frame2

frame2['debt'].notna()

frame2['debt'].isna().sum()

frame2.columns

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

0    False
1    False
2    False
3    False
4    False
5    False
Name: debt, dtype: bool

6

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [176]:
frame2

frame2['pop'].dtype

np.ceil( frame2['pop'] ).astype('i2')

np.floor( frame2['pop'] ).astype('i2')

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

dtype('float64')

0    2
1    2
2    4
3    3
4    3
5    4
Name: pop, dtype: int16

0    1
1    1
2    3
3    2
4    2
5    3
Name: pop, dtype: int16

In [177]:
frame3 = frame2.copy()

# Change labels to strings
frame3.index = ['a', 'b', 'c', 'd', 'e', 'f']

frame3

frame3.loc['a'] # refrence label to fetch record

frame3.iloc[1] # refrence index to fetch record

   year   state  pop debt
a  2000    Ohio  1.5  NaN
b  2001    Ohio  1.7  NaN
c  2002    Ohio  3.6  NaN
d  2001  Nevada  2.4  NaN
e  2002  Nevada  2.9  NaN
f  2003  Nevada  3.2  NaN

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: a, dtype: object

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: b, dtype: object

In [178]:
frame2['debt']=16.5
frame2

frame2['debt'] = np.linspace(11, 20, 6)
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

   year   state  pop  debt
0  2000    Ohio  1.5  11.0
1  2001    Ohio  1.7  12.8
2  2002    Ohio  3.6  14.6
3  2001  Nevada  2.4  16.4
4  2002  Nevada  2.9  18.2
5  2003  Nevada  3.2  20.0

In [179]:
data = {
    'state': ['Ohio', 'Texas', 'Washingtion', 'California', 'New York', 'Nevada'],
    'year': [2000, 2001, 2002, 2006, 2009, 2013],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}
frame4 = pd.DataFrame(data, columns=['year', 'state', 'pop'])

val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five']) 
frame4['debt'] = val # When inserting a Series into a DataFrame, the labels MUST match.

frame4

   year        state  pop  debt
0  2000         Ohio  1.5   NaN
1  2001        Texas  1.7   NaN
2  2002  Washingtion  3.6   NaN
3  2006   California  2.4   NaN
4  2009     New York  2.9   NaN
5  2013       Nevada  3.2   NaN

In [180]:
frame4['eastern'] = ( frame['state'] == 'Ohio' )

frame4

del frame4['eastern']

frame4

   year        state  pop  debt  eastern
0  2000         Ohio  1.5   NaN     True
1  2001        Texas  1.7   NaN     True
2  2002  Washingtion  3.6   NaN     True
3  2006   California  2.4   NaN    False
4  2009     New York  2.9   NaN    False
5  2013       Nevada  3.2   NaN    False

   year        state  pop  debt
0  2000         Ohio  1.5   NaN
1  2001        Texas  1.7   NaN
2  2002  Washingtion  3.6   NaN
3  2006   California  2.4   NaN
4  2009     New York  2.9   NaN
5  2013       Nevada  3.2   NaN

In [181]:
population = {
    'Ohio': {
        2000: 1.5, 
        2001: 1.7,
        2002: 3.6,
    },
    'Nevada': {
        2001: 2.4,
        2002: 2.9,
        2005: 3.2,
    }
}

frame5 = pd.DataFrame(population)
frame5.shape 

# uncomment and observe axis wise behaviour
# frame5.isna().sum(axis=1)
# frame5.isna().sum(axis=1)

'NaN:'
frame5.isna().sum()

frame5.T

(4, 2)

'NaN:'

Ohio      1
Nevada    1
dtype: int64

        2000  2001  2002  2005
Ohio     1.5   1.7   3.6   NaN
Nevada   NaN   2.4   2.9   3.2

In [186]:
pdata = {
    'Ohio': frame5['Ohio'][:-1],
    'Nevada': frame5['Nevada'][:2]
}
frame5

frame5['Ohio'][:-1]
frame5['Nevada'][:2]

pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9
2005   NaN     3.2

2000    1.5
2001    1.7
2002    3.6
Name: Ohio, dtype: float64

2000    NaN
2001    2.4
Name: Nevada, dtype: float64

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     NaN

In [187]:
frame5

frame5.to_numpy()

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9
2005   NaN     3.2

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9],
       [nan, 3.2]])

### Reindexing

In [211]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'], dtype = np.float32)
obj

obj2=  obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

'iloc[]: for index'
obj2.iloc[0]

'loc[]: for label'
obj2.loc['e']

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float32

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float32

'iloc[]: for index'

-5.3

'loc[]: for label'

nan

In [216]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index = [0, 2, 4])

obj3.str.title()

0      Blue
2    Purple
4    Yellow
dtype: object

0      blue
2    purple
4    yellow
dtype: object

In [377]:
frame = pd.DataFrame(np.arange(9).reshape(3,3), 
                     index = ['a', 'c', 'd'], 
                     columns = ['Ohio', 'Texas', 'California'])

frame
frame2 = frame.reindex(['a', 'c', 'd', 'b'])
frame2


states = ['Texas', 'Utah', 'California']

frame.reindex(columns=states)
frame

nan_values = ( frame == np.nan)
frame_01 = frame.reindex(states, axis='columns')

frame_01[nan_values]

frame == np.nan

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

   Ohio  Texas  California
a   0.0    1.0         2.0
c   3.0    4.0         5.0
d   6.0    7.0         8.0
b   NaN    NaN         NaN

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

   Texas  Utah  California
a    NaN   NaN         NaN
c    NaN   NaN         NaN
d    NaN   NaN         NaN

    Ohio  Texas  California
a  False  False       False
c  False  False       False
d  False  False       False

In [239]:
frame = pd.DataFrame(np.arange(9).reshape(3,3), 
                     index = ['a', 'c', 'd'], 
                     columns = ['Ohio', 'Texas', 'California'])

frame2 = frame.reindex(['a', 'c', 'd', 'b'], fill_value=np.mean(np.arange(1,10)), copy=False )
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
c   3.0    4.0         5.0
d   6.0    7.0         8.0
b   5.0    5.0         5.0

In [277]:
frame.loc['a'][:]


frame.loc[['a', 'd'], ['Ohio', 'California']]

Ohio          0
Texas         1
California    2
Name: a, dtype: int32

   Ohio  California
a     0           2
d     6           8

### Dropping Entries from an Axis

In [288]:
obj = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e']).astype('i8')
obj

new_obj = obj.drop('a')
new_obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

b    1
c    2
d    3
e    4
dtype: int64

In [304]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])

data
data.drop(index = ['Ohio', 'Utah']) #not permanent unless 'inplace = True'
data

data.drop(columns = ['one', 'four'], index = ['Ohio'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

          one  two  three  four
Colorado    4    5      6     7
New York   12   13     14    15

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

          two  three
Colorado    5      6
Utah        9     10
New York   13     14

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [311]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])

data
data.drop(index = ['Ohio'], inplace = True) #permanet drop from dataframe
data

data.drop('two', axis=1)
data

data.drop(['two', 'one'], axis='columns')
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

          one  three  four
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

          three  four
Colorado      6     7
Utah         10    11
New York     14    15

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [317]:
data = pd.Series(['a', 'b', 'c'], index = [1, 3, 5])
data

data[1:3] # index[1,2]

1    a
3    b
5    c
dtype: object

3    b
5    c
dtype: object

In [324]:
data.iloc[0]

data.iloc[1:3]

data.loc[1]

data.loc[1:3]

'a'

3    b
5    c
dtype: object

'a'

1    a
3    b
dtype: object

In [406]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                    'New York': 141297, 'Florida': 170312,
                        'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                    'New York': 19651127, 'Florida': 19552860,
                        'Illinois': 12882135})

data = pd.DataFrame({'area': area, 'pop':pop})
data

data2 = pd.DataFrame(data, index = sorted(data.index))
data2


# # never do this. sorting taechnique good for array or series but not for daraframe 
# # cus it looks sorting a feature(column) in isloation without considering the other features(columns) for same records(row)
# data2['area'] = sorted(data2['area']) 
# data2

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

              area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135
New York    141297  19651127
Texas       695662  26448193

In [373]:
data

data['area']
data.area 

data.area is data['area'] # its working well cus column names are strings

data.pop is data['pop'] # cus if confilcts with metond .pop()

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

True

False

In [408]:
verify = pd.Series(['area', 'pop', 19])

data3 = data.reindex(columns = verify)
data3[19] = np.linspace(1, 76, data['area'].size)

data3[19]
# data3.19 # SyntaxError: invalid syntax

data4 = data3.copy()
data4[19] = np.linspace(1, 76, data['area'].size)
data4

California     1.00
Texas         19.75
New York      38.50
Florida       57.25
Illinois      76.00
Name: 19, dtype: float64

              area       pop     19
California  423967  38332521   1.00
Texas       695662  26448193  19.75
New York    141297  19651127  38.50
Florida     170312  19552860  57.25
Illinois    149995  12882135  76.00

In [407]:
data

data['density'] = data['pop']/data['area']
data

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

              area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [426]:
data.values

data.T

data.iloc[:3, :2]

data.loc[:'Illinois', :'pop']

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

           California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [429]:
data

data.loc[data.density > 100]

data.loc[data.density > 100, ['pop', 'density']]

              area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

            area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

               pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [433]:
data.iloc[0, 2]
data.iloc[0, 2] = round(data.iloc[0, 2], 0)
data

90.0

              area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

#### while indexing refers to columns, slicing refers to rows

In [438]:
data

data[1:3]

data['Texas': 'Illinois']

data[data.density > 87]

              area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

            area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

            area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

              area       pop     density
California  423967  38332521   90.000000
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121

# Task

A logistics company in Lahore received their monthly branch data as a raw dump. Before any report goes to management, the data needs to be structured, audited, and enriched with derived metrics. Your job is to build the operations register and make it analysis-ready.

In [442]:
import pandas as pd
import numpy as np

Part A — Construction    Build the DataFrame with correct dtypes and index.
                         Think: what happens if dtype is wrong at creation?
                         Why: silent dtype errors compound — catch at source.

Part B — Audit           Verify structure before touching anything.
                         Think: what would a null or wrong dtype break downstream?
                         Why: auditing first is the habit that prevents silent bugs.

Part C — Access          Extract data by column, by row, by condition.
                         Think: when does access return a Series vs DataFrame?
                         Why: wrong shape breaks every downstream operation.
Part D — Transformation  Derive a new column, clean an existing one.
                         Think: which string issue will cause label mismatches later?
                         Why: cleaning at source costs one line, fixing later costs hours.

Part E — Validation      Confirm memory behavior after extraction.
                         Think: is your extraction a view or a copy?
                         Why: assuming wrong leads to silent data mutation bugs.

In [515]:
usd_rate = 280
branches = ['Lahore', 'Multan', 'Sialkot', 'Kanewal'] 

employees = pd.DataFrame({
    'name':['Ali Raza', 'sara Khan', 'USMAN MaliK', 'MunaWAr iqbal'],
    'salary': np.linspace(9000, 600_000, 4),
    'department': ['Sales', 'Enginnering', 'Sales', 'Accounts'],
    'active': [True, True, False, True]
}, index = branches)

# employees.reindex(index = branches) #its more of a filter to show the specified data
employees['name'] = employees['name'].str.title()
employees['salary_usd'] = (employees['salary']/usd_rate).round(2).astype('f4')

# employees.loc[employees['salary']>100_000]

# salaries = employees['']
# employees.info()

employees = pd.DataFrame(employees).astype({'name': 'string', 'salary': 'i4', 'department': 'str', 'active': 'bool'})

# employees.info()

salaries = employees['salary']
report = employees[['name', 'salary_usd']]
active_only = employees[employees['active'] == True]
lahore = employees.loc['Lahore']

np.shares_memory(employees, employees['salary']), np.shares_memory(salaries, employees['salary']), np.shares_memory(salaries, employees)

employees.shape
find_ = employees.columns.tolist()
employees.isna().sum()

find_

(False, True, False)

(4, 5)

name          0
salary        0
department    0
active        0
salary_usd    0
dtype: int64

['name', 'salary', 'department', 'active', 'salary_usd']

# Project

A Lahore-based logistics company tracks deliveries, revenue, and performance across 4 cities. The raw data arrived with inconsistent index formatting and no derived metrics. Management needs a clean, enriched DataFrame with city-level insights before end of day. Your job: build it correctly, fix what is broken, enrich it, extract answers, and verify your work.

In [576]:
import pandas as pd
import numpy as np

CITIES = ['Lahore', 'karachi', 'ISLAMABAD', 'Peshawar']
USD_RATE = 280

operations = pd.DataFrame({
    'deliveries':   np.array([340, 520, 210, 180], dtype=np.int32),
    'revenue_pkr':  np.array([850000, 1200000, 620000, 490000], dtype=np.int32),
    'avg_delay':    np.array([1.2, 2.8, 0.9, 3.4], dtype=np.float32),
    'fleet_size':   np.array([12, 18, 8, 7], dtype=np.int32),
    'on_time_rate': np.array([0.91, 0.74, 0.95, 0.68], dtype=np.float32),
}, index=CITIES)

operations

# operations.info()
operations.isna().sum()
operations.index = operations.index.str.title() 
# with the wrong capitization isb and ISB, both are different sting and they can cause np.nan data in the frames
operations['revenue_usd'] = (operations['revenue_pkr']/ USD_RATE ).round()
operations['efficiency_score'] = (operations['on_time_rate']/(operations['avg_delay']+1) )

operations['efficiency_score'] = operations['efficiency_score'].round(2)
best_city = operations['efficiency_score'].idxmax()
worst_city = operations['efficiency_score'].idxmin()

filtered = operations[ (operations['on_time_rate'] > .8)  &  (operations['fleet_size'] > 10) ] 
sorted_result = filtered.sort_values(by='efficiency_score', ascending=False)
sorted_result

filtered_results = sorted_result
print(f'Does bonus feature exist? {'bonus' in operations.columns}')
np.shares_memory(sorted_result, operations), np.shares_memory(best_city, operations['efficiency_score']),

           deliveries  revenue_pkr  avg_delay  fleet_size  on_time_rate
Lahore            340       850000        1.2          12          0.91
karachi           520      1200000        2.8          18          0.74
ISLAMABAD         210       620000        0.9           8          0.95
Peshawar          180       490000        3.4           7          0.68

deliveries      0
revenue_pkr     0
avg_delay       0
fleet_size      0
on_time_rate    0
dtype: int64

,deliveries,revenue_pkr,avg_delay,fleet_size,on_time_rate,revenue_usd,efficiency_score
Lahore,340,850000,1.2,12,0.91,3036.0,0.41

Does bonus feature exist? False

(False, False)